# coding: utf-8

"""
    WillItSync

    Sitemap Checker  # noqa: E501

    The version of the OpenAPI document: 1.1.1
    Contact: jevans97@utk.edu
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class LogEntry(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'level': 'int',
        'timestamp': 'datetime',
        'msg': 'str'
    }

    attribute_map = {
        'level': 'level',
        'timestamp': 'timestamp',
        'msg': 'msg'
    }

    def __init__(self, level=None, timestamp=None, msg=None):  # noqa: E501
        """LogEntry - a model defined in OpenAPI"""  # noqa: E501

        self._level = None
        self._timestamp = None
        self._msg = None
        self.discriminator = None

        self.level = level
        self.timestamp = timestamp
        self.msg = msg

    @property
    def level(self):
        """Gets the level of this LogEntry.  # noqa: E501

        Logging level for entry. DEBUG=10, INFO=20, WARNING=30, ERROR=40, FATAL=50   # noqa: E501

        :return: The level of this LogEntry.  # noqa: E501
        :rtype: int
        """
        return self._level

    @level.setter
    def level(self, level):
        """Sets the level of this LogEntry.

        Logging level for entry. DEBUG=10, INFO=20, WARNING=30, ERROR=40, FATAL=50   # noqa: E501

        :param level: The level of this LogEntry.  # noqa: E501
        :type: int
        """
        if level is None:
            raise ValueError("Invalid value for `level`, must not be `None`")  # noqa: E501

        self._level = level

    @property
    def timestamp(self):
        """Gets the timestamp of this LogEntry.  # noqa: E501

        Timestamp for log entry  # noqa: E501

        :return: The timestamp of this LogEntry.  # noqa: E501
        :rtype: datetime
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this LogEntry.

        Timestamp for log entry  # noqa: E501

        :param timestamp: The timestamp of this LogEntry.  # noqa: E501
        :type: datetime
        """
        if timestamp is None:
            raise ValueError("Invalid value for `timestamp`, must not be `None`")  # noqa: E501

        self._timestamp = timestamp

    @property
    def msg(self):
        """Gets the msg of this LogEntry.  # noqa: E501

        The logged message.  # noqa: E501

        :return: The msg of this LogEntry.  # noqa: E501
        :rtype: str
        """
        return self._msg

    @msg.setter
    def msg(self, msg):
        """Sets the msg of this LogEntry.

        The logged message.  # noqa: E501

        :param msg: The msg of this LogEntry.  # noqa: E501
        :type: str
        """
        if msg is None:
            raise ValueError("Invalid value for `msg`, must not be `None`")  # noqa: E501

        self._msg = msg

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LogEntry):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
