# coding: utf-8

"""
    WillItSync

    Sitemap Checker  # noqa: E501

    The version of the OpenAPI document: 1.1.1
    Contact: jevans97@utk.edu
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class RobotsFile(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'url': 'str',
        'log': 'list[LogEntry]',
        'evaluated_date': 'datetime',
        'sitemaps': 'list[str]'
    }

    attribute_map = {
        'url': 'url',
        'log': 'log',
        'evaluated_date': 'evaluated_date',
        'sitemaps': 'sitemaps'
    }

    def __init__(self, url=None, log=None, evaluated_date=None, sitemaps=None):  # noqa: E501
        """RobotsFile - a model defined in OpenAPI"""  # noqa: E501

        self._url = None
        self._log = None
        self._evaluated_date = None
        self._sitemaps = None
        self.discriminator = None

        self.url = url
        self.log = log
        self.evaluated_date = evaluated_date
        self.sitemaps = sitemaps

    @property
    def url(self):
        """Gets the url of this RobotsFile.  # noqa: E501

        The URL for the robots.txt file  # noqa: E501

        :return: The url of this RobotsFile.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this RobotsFile.

        The URL for the robots.txt file  # noqa: E501

        :param url: The url of this RobotsFile.  # noqa: E501
        :type: str
        """
        if url is None:
            raise ValueError("Invalid value for `url`, must not be `None`")  # noqa: E501

        self._url = url

    @property
    def log(self):
        """Gets the log of this RobotsFile.  # noqa: E501


        :return: The log of this RobotsFile.  # noqa: E501
        :rtype: list[LogEntry]
        """
        return self._log

    @log.setter
    def log(self, log):
        """Sets the log of this RobotsFile.


        :param log: The log of this RobotsFile.  # noqa: E501
        :type: list[LogEntry]
        """
        if log is None:
            raise ValueError("Invalid value for `log`, must not be `None`")  # noqa: E501

        self._log = log

    @property
    def evaluated_date(self):
        """Gets the evaluated_date of this RobotsFile.  # noqa: E501

        The time stamp for when the evaluation of robots.txt was initiated.   # noqa: E501

        :return: The evaluated_date of this RobotsFile.  # noqa: E501
        :rtype: datetime
        """
        return self._evaluated_date

    @evaluated_date.setter
    def evaluated_date(self, evaluated_date):
        """Sets the evaluated_date of this RobotsFile.

        The time stamp for when the evaluation of robots.txt was initiated.   # noqa: E501

        :param evaluated_date: The evaluated_date of this RobotsFile.  # noqa: E501
        :type: datetime
        """
        if evaluated_date is None:
            raise ValueError("Invalid value for `evaluated_date`, must not be `None`")  # noqa: E501

        self._evaluated_date = evaluated_date

    @property
    def sitemaps(self):
        """Gets the sitemaps of this RobotsFile.  # noqa: E501

        A list of sitemap URLs retrieved from the robots.txt file   # noqa: E501

        :return: The sitemaps of this RobotsFile.  # noqa: E501
        :rtype: list[str]
        """
        return self._sitemaps

    @sitemaps.setter
    def sitemaps(self, sitemaps):
        """Sets the sitemaps of this RobotsFile.

        A list of sitemap URLs retrieved from the robots.txt file   # noqa: E501

        :param sitemaps: The sitemaps of this RobotsFile.  # noqa: E501
        :type: list[str]
        """
        if sitemaps is None:
            raise ValueError("Invalid value for `sitemaps`, must not be `None`")  # noqa: E501

        self._sitemaps = sitemaps

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RobotsFile):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
