# coding: utf-8

"""
    WillItSync

    Provides various methods for retrieving, parsing, and validating the  various portions of a web harvesting workflow.   # noqa: E501

    The version of the OpenAPI document: 1.1.1
    Contact: jevans97@utk.edu
    Generated by: https://openapi-generator.tech
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "openapi-client"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="WillItSync",
    author_email="jevans97@utk.edu",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "WillItSync"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description="""\
    Provides various methods for retrieving, parsing, and validating the  various portions of a web harvesting workflow.   # noqa: E501
    """
)
