# coding: utf-8

"""
    WillItSync

    Sitemap Checker  # noqa: E501

    The version of the OpenAPI document: 1.1.1
    Contact: jevans97@utk.edu
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.users_api import UsersApi  # noqa: E501
from openapi_client.rest import ApiException


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.users_api.UsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_validate_metadata(self):
        """Test case for get_validate_metadata

        Retrieve and validate a science metadata XML document  # noqa: E501
        """
        pass

    def test_get_validate_so(self):
        """Test case for get_validate_so

        Retrieve and validate a schema.org JSON-LD document  # noqa: E501
        """
        pass

    def test_parse_langingpage(self):
        """Test case for parse_langingpage

        Extract schema.org metadata  # noqa: E501
        """
        pass

    def test_parse_robots(self):
        """Test case for parse_robots

        Parses robots.txt to find sitemap(s)  # noqa: E501
        """
        pass

    def test_parse_sitemap(self):
        """Test case for parse_sitemap

        Parses sitemap.xml  # noqa: E501
        """
        pass

    def test_validate_metadata(self):
        """Test case for validate_metadata

        Validate provided schema.org JSON-LD document  # noqa: E501
        """
        pass

    def test_validate_so(self):
        """Test case for validate_so

        Validate provided schema.org JSON-LD document  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
