# coding: utf-8

"""
    WillItSync

    Sitemap Checker  # noqa: E501

    The version of the OpenAPI document: 1.1.1
    Contact: jevans97@utk.edu
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.sitemap import Sitemap  # noqa: E501
from openapi_client.rest import ApiException


class TestSitemap(unittest.TestCase):
    """Sitemap unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSitemap(self):
        """Test Sitemap"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.sitemap.Sitemap()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
